# Jenkinsfile
pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE = 'bus-ticket-image'
    }
    
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Jackson590/23RP00810-project-bus-ticket-booking-system.git'
            }
        }
        
        stage('Build') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE:latest .'
            }
        }
        
        stage('Test') {
            steps {
                sh 'npm install && npm test'
            }
        }
        
        stage('Push') {
            steps {
                withDockerRegistry([ credentialsId: 'docker-hub-credentials' ]) {
                    sh 'docker push $DOCKER_IMAGE:latest'
                }
            }
        }
        
        stage('Deploy') {
            steps {
                sshagent(['server-ssh-key']) {
                    sh '''
                        ssh $DEPLOY_USER@$DEPLOY_HOST "
                            docker pull $DOCKER_IMAGE:latest
                            docker stop myapp || true
                            docker rm myapp || true
                            docker run -d -p 4000:4000 --name myapp $DOCKER_IMAGE:latest
                        "
                    '''
                }
            }
        }
    }
}
