# GitHub Actions Workflow
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test
      
      - name: Build Docker image
        run: |
          docker build -t bus-ticket-image:latest .
          echo "APP_VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
      
      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag myapp:latest mydockerhub/myapp:${{ env.APP_VERSION }}
          docker push mydockerhub/myapp:${{ env.APP_VERSION }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull mydockerhub/myapp:${{ env.APP_VERSION }}
            docker stop myapp || true
            docker rm myapp || true
            docker run -d -p 4000:4000 --name bus-ticket-image:${{ env.APP_VERSION }}
